baseURL = "https://renz7.github.io/"
languageCode = "zh-cn"
title = "Ren7's daily note."
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Renz7"
  description = "inner peace"
  github = "Renz7"
  stackoverflow="15373262"
  email = "Renz7@outlook.com"
  url = "https://github.com/renz7"
  utterances = "Renz7/Renz7.github.io"
  keywords = "blog,python,golang,java,k8s,backend"
  rss = true
  lastmod = true
  enableGitalk = true
  userStatusEmoji = "😀"
  favicon = "/images/avatar.png"
  location = "Shenzhen,China"

  [[params.links]]
    title = "Theme From"
    href = "https://github.com/meik2333"
    icon = "https://meik2333.com/images/avatar.png"

  [params.gitalk]
    clientID = "e82b43a7dc240d5cb4bb" 
    clientSecret = "565d40b4ee93c33c90a8b6005a805777c693c3b2" 
    repo = "Renz7.github.io"
    owner = "renz7"
    admin = "renz7"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 30
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

