baseURL = "https://renz7.github.io/"
languageCode = "zh-cn"
title = "Ren777's blog."
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableInlineShortcodes = true
enableEmoji = true

[params]
  author = "Renz7"
  description = "Care will kill the cat."
  github = "Renz7"
  stackoverflow="renz7"
  email = "Renz7@outlook.com"
  url = "https://renz7.github.io/"
  keywords = "blog, code man,python,golang"
  rss = false
  lastmod = true
  favicon = "/images/avator.png"
  location = "Shenzhen,China"

  [[params.links]]
    title = "Theme From"
    href = "https://github.com/meik2333"
    icon = "https://meik2333.com/images/avatar.png"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

