baseURL = "https://renz7.github.io/"
languageCode = "zh-cn"
title = "Ren7's daily note."
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableInlineShortcodes = true
enableEmoji = true
enableGitInfo = true

[params]
  author = "Renz7"
  description = "Care will kill the cat."
  github = "Renz7"
  stackoverflow="15373262"
  email = "Renz7@outlook.com"
  url = "https://github.com/renz7"
  keywords = "blog,python,golang,java,k8s,backend"
  rss = false
  lastmod = true
  favicon = "/images/avatar.png"
  location = "Shenzhen,China"

  [[params.links]]
    title = "Theme From"
    href = "https://github.com/meik2333"
    icon = "https://meik2333.com/images/avatar.png"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

